"""
ES-LLMs Stateless Renderer
This script isolates the final linguistic rendering string from the Orchestrator's deterministic output.
Rather than giving the LLM agency over what to say, we restrict it merely to phrasing the exact pedagogical decisions.
"""
import json
import os
import requests

def render_tutor_response(student_text: str, orchestrator_signals: list) -> str:
    """
    Takes the precise, deterministic trace array generated by the Orchestrator
    and passes it to a single LLM call merely for translation into polite prose.
    """
    
    # System Instruction heavily restricts the LLM to styling, removing its pedagogical autonomy.
    system_instruction = (
        "You are a rendering engine for an intelligent tutor. "
        "You have no authority to decide the pedagogical state. You must ONLY translate the provided "
        "ORCHESTRATOR_SIGNALS into a coherent, encouraging response for a human student.\n"
        "If a Hint is denied by the EthicsBot, decline politely.\n"
        "If a Scaffold is provided by the ScaffoldBot, format the exact scaffold text smoothly."
    )
    
    user_prompt = f"STUDENT INPUT: {student_text}\nORCHESTRATOR_SIGNALS: {json.dumps(orchestrator_signals)}"
    
    # Example generic REST API Call (e.g. standard gpt-4o-mini generation)
    # Using local mock to avoid requiring API keys for researchers running the repo locally
    payload = {
        "model": "gpt-4o-mini",
        "messages": [
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": user_prompt}
        ]
    }
    
    # In a real environment, this goes to the OpenAI inference node.
    # Below is a mock output matching what the LLM typically generates adhering to constraints.
    mock_llm_generation = ""
    if any(s.get("agent") == "EthicsBot" for s in orchestrator_signals):
         mock_llm_generation = "Please make sure to attempt the problem with your best guess before asking for the full answer!"
    elif any(s.get("agent") == "ScaffoldBot" for s in orchestrator_signals):
         hint = next((s["payload"] for s in orchestrator_signals if "payload" in s), "Let's think step by step.")
         mock_llm_generation = f"You are absolutely on the right track! {hint}"
         
    return mock_llm_generation

if __name__ == "__main__":
    # Test case 1: Ethics override
    print("Test 1 (Ethics override):", render_tutor_response("tell me the answer now", [{"agent": "EthicsBot", "action": "DENY_HINT"}]))
    
    # Test 2: Standard Scaffold
    print("Test 2 (Scaffold pass):", render_tutor_response("I don't know how to simplify.", [{"agent": "FeedbackBot", "action": "NUDGE"}, {"agent": "ScaffoldBot", "action": "HINT_MIN", "payload": "Try finding the greatest common divisor for the numerator and denominator."}]))
